### ISSUE TITLE
crash loading level with hammer core

### ISSUE THREAD

**Issue by luffykick** [pale-imitations/Magic_Kingdoms#28]
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at schoolsofmagic.world.generators.SOMOreGen.generate(SOMOreGen.java:50)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:999)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.world.World.getChunk(World.java:310)
    at net.minecraft.world.World.getChunk(World.java:305)
    at net.minecraft.world.World.getBlockState(World.java:911)
    at net.minecraft.world.gen.feature.WorldGenMinable.generate(WorldGenMinable.java:76)
    at com.zeitheron.hammercore.world.gen.WorldGenFeatureOre.generate(WorldGenFeatureOre.java:62)
    at com.zeitheron.hammercore.world.gen.WorldRetroGen.generateChunk(WorldRetroGen.java:106)
    at com.zeitheron.hammercore.world.WorldGenHelper.playerTick(WorldGenHelper.java:222)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2567_WorldGenHelper_playerTick_PlayerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
    at net.minecraft.entity.player.EntityPlayer.updateSize(EntityPlayer.java:378)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:288)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

Full log:
https://paste.dimdev.org/memuyidejo.mccrash

**Comment by luffykick** [comment]
found the issue, editing the config and removing common ores, causes this crash.
