### ISSUE TITLE
Can't trade with villagers in multiplayer

### ISSUE THREAD

**Issue by Earlh21** [pale-imitations/Magic_Kingdoms#7]
My friends and I are playing on a private server with a custom modpack. Mods are listed [here.](https://pastebin.com/8PcdFPzm)
We can't trade with any villagers, including the NPCs from Electroblob's Wizardry. In singleplayer, however, we can trade just fine.

I found an exception being thrown in the server console every time you try to trade with a villager. [Here it is.](https://pastebin.com/YzHvuAnj)

Removing Magic Kingdoms from this pack fixes the issue.

**Comment by rgooch42** [comment]
I will add to this that I was noticing item frame issues with Magic Kingdoms installed. Is it possible that this is a bug with entities? My issue was specifically interacting with item frames and TekTopia. Removing Magic Kingdoms also fixed my issue.

I'd really like to see if this can be resolved, I'd love to play with both.

Error Below:
`[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$EntityInteract@11595ecf:
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at schoolsofmagic.util.handlers.VoidCharmInteractionHandler.voidClick(VoidCharmInteractionHandler.java:28) ~[VoidCharmInteractionHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1254_VoidCharmInteractionHandler_voidClick_EntityInteract.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:1116) [ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1194) [aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1075) [pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by pale-imitations** [comment]
Thank you for letting me know, I think I've fixed the bug, so hopefully, this shouldn't be an issue in the next update
